server:
  port: 12000

app:
  file:
    upload-dir: file:///var/www/token/uploads/

spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      location: /var/www/token/temp
      max-file-size: 5000MB
      max-request-size: 5000MB

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: info
    _org.springframework.web.servlet.HandlerMapping.Mappings: info
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: trace

---

spring:
  config:
    activate:
      on-profile : dev

  datasource:
    first:
      jdbc-url: jdbc:mariadb://192.168.0.80:3306/febc?useUnicode=true&characterEncoding=utf8
      username: root
      password: tjdrhd5@
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view : false
    first:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true #To beautify or pretty print the SQL
          show_sql: true #show sql
          highlight_sql : true

# mysql / mariadb 암호화 복호화 비밀 키
aes:
  key: F63VGK1W27GnwTZBL51piTJxtdlfK50A

jwt:
  secret-key: Qiws8sD4mU7CSKhUX6q82t69KEkp7K9ff2QCu4k9gDJNgFUJ
  access-expire: 86400 # 단위(초)
  refresh-expire: 86400 # 단위(초)

springfox:
  documentation:
    enabled: true